### ISSUE TITLE
Τοποθέτηση δεικτών σε κάθε τοποθεσία ενδιαφέροντος.

### ISSUE THREAD

**Issue by Stathis001** [Stathis001/Tourist_Guide#11]
Το μόνο που χρειάζεται είναι να βάλετε τις συντεταγμένες από το google maps στον κώδικα της MarketLoader κλάσης ακριβώς όπως είναι και το πρώτο παράδειγμα.

**Comment by Argiris2000** [comment]
manager.addMarker(2, 41.09835129725971, 23.551927608268336,"Lofos Koyla");
        manager.addMarker(3, 41.09156654135183, 23.559917963233605,"Achmet Pasa Tzami");
        manager.addMarker(4, 41.08828964518851, 23.553439602363994,"Ζιντζιρλί Τζαμί");
        manager.addMarker(5, 41.09146333054632, 23.55051494660206,"Liberty Square");
        manager.addMarker(6, 41.090984162331786, 23.54966866588395,"Archeological Museum of Serres (Bezesteni)");
        manager.addMarker(7, 41.10059767457084, 23.57097613512557,"Natural History Museum");
        manager.addMarker(8, 41.10434890738389, 23.553423758489348,"Agioi Anargyroi Valley");
    }

**Comment by panostsili23** [comment]
manager.addMarker(9, 41.07791797232521, 23.542626119426355,"Intercity Bus Station of Serres");
manager.addMarker(10, 41.07329171632362, 23.5470893150212,"Serres Camp");
manager.addMarker(11, 41.09486734480665, 23.558418965379346,"Philippos Xenia Hotel");
manager.addMarker(12, 41.10347193488058, 23.549222483272818,"Elpida Resort & Spa");
manager.addMarker(13, 41.08930648512539, 23.527421488950267,"Serres National Stadium");
manager.addMarker(14, 41.09293009514462, 23.55736205023394,"Serres State Health Center");
manager.addMarker(
manager.addMarker(
manager.addMarker(

**Comment by panostsili23** [comment]
manager.addMarker(9, 41.07791797232521, 23.542626119426355,"Intercity Bus Station of Serres");
manager.addMarker(10, 41.07329171632362, 23.5470893150212,"Serres Camp");
manager.addMarker(11, 41.09486734480665, 23.558418965379346,"Philippos Xenia Hotel");
manager.addMarker(12, 41.10347193488058, 23.549222483272818,"Elpida Resort & Spa");
manager.addMarker(13, 41.08930648512539, 23.527421488950267,"Serres National Stadium");
manager.addMarker(14, 41.09293009514462, 23.55736205023394,"Serres State Health Center");
manager.addMarker(15, 41.0941120281705, 23.546161726125494,"Kalithea Serres");
manager.addMarker(16, 41.097588736734345, 23.551225736764437,"Cityζεν WINE · BAR · RESTAURANT");
manager.addMarker(17, 41.082807410884556, 23.5425353795879,"Fire Service");
manager.addMarker(18, 41.07275655544222, 23.51766362781244,"Serres Racing Circuit");
manager.addMarker(19, 41.06602011402373, 23.54131497674441,"LA VITA CENTER");
manager.addMarker(20, 41.084803498471516, 23.546518769143844,"Serres Municipal Stadium");
manager.addMarker(21, 41.08315378520309, 23.551668610294023,"Ελλήνων Γεύσεις");
manager.addMarker(22, 41.08084088215488, 23.541583504790097,"Bruno Coffee Stores");
manager.addMarker(23, 41.08787638344969, 23.541433300952594,"ACS Courier");
manager.addMarker(24, 41.090423204868415, 23.58244886315631,"General Hospital of Serres");
