### ISSUE TITLE
Ενεργοποίηση λειτουργείας οδηγιών προς τοποθεσίας σημείου.

### ISSUE THREAD

**Issue by Stathis001** [Stathis001/Tourist_Guide#18]
Πιθανότατα λειτουργεία μιας ξεχωριστής κλάσης που ακόμα δεν υπάρχει μέσα απο την MapActivity.java .

**Comment by Argiris2000** [comment]
LocationHandler
public void startDirections(double destinationLatitude, double destinationLongitude) {
    // Έλεγχος αν έχουν δοθεί τα απαραίτητα δικαιώματα
    if (ActivityCompat.checkSelfPermission(activity, Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED) {
        // Έλεγχος αν έχει ενεργοποιηθεί η λειτουργία τοποθεσίας
        if (googleMap.isMyLocationEnabled()) {
            // Λήψη της τρέχουσας τοποθεσίας
            fusedLocationClient.getLastLocation().addOnSuccessListener(activity, new OnSuccessListener<Location>() {
                @Override
                public void onSuccess(Location location) {
                    if (location != null) {
                        // Έναρξη των οδηγιών προς την προορισμένη τοποθεσία
                        Uri gmmIntentUri = Uri.parse("google.navigation:q=" + destinationLatitude + "," + destinationLongitude);
                        Intent mapIntent = new Intent(Intent.ACTION_VIEW, gmmIntentUri);
                        mapIntent.setPackage("com.google.android.apps.maps");
                        if (mapIntent.resolveActivity(activity.getPackageManager()) != null) {
                            activity.startActivity(mapIntent);
                        }
                    }
                }
            });
        } else {
            // Ενεργοποίηση της λειτουργίας τοποθεσίας
            enableMyLocation();
        }
    } else {
        // Ζήτηση δικαιώματος πρόσβασης στην τοποθεσία
        ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.ACCESS_FINE_LOCATION}, LOCATION_PERMISSION_REQUEST_CODE);
    }
}
