### ISSUE TITLE
Θέλουμε μικρή μετατροπή του start_screen.xml 

### ISSUE THREAD

**Issue by Stathis001** [Stathis001/Tourist_Guide#22]

**Comment by Argiris2000** [comment]
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    tools:context=".MainActivity">

    
    <ImageView
        android:id="@+id/backgroundImageView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:src="@drawable/received_663824995734600"
        android:scaleType="centerCrop"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"/>

    
    <Button
        android:id="@+id/startButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/start"
        android:textSize="18sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/backgroundImageView"
        app:layout_constraintVertical_bias="0.8"/>
</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by Stathis001** [comment]
<TextView
            android:id="@+id/messageTextView"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Discover the beauty of the world"
            android:textColor="#FFFF00"
            android:textSize="28sp"
            android:background="@color/quantum_black_hint_text"
            android:layout_above="@id/startButton"
            android:layout_centerHorizontal="true"
            android:layout_marginBottom="16dp"/>

**Comment by Stathis001** [comment]
"<TextView
            android:id="@+id/messageTextView"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Discover the beauty of the world"
            android:textColor="#FFFF00"
            android:textSize="28sp"
            android:background="@color/quantum_black_hint_text"
            android:layout_above="@id/startButton"
            android:layout_centerHorizontal="true"
            android:layout_marginBottom="16dp"/>"
